import { Octokit } from '@octokit/rest';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

dotenv.config();

/**
 * GitHubExportAgent: Pushes generated files to a new GitHub repository.
 */
export async function runGitHubExportAgent(files: any[], demoName: string): Promise<string> {
  const token = process.env.GITHUB_TOKEN;
  const repoName = demoName.toLowerCase().replace(/[^a-z0-9-_]/g, '-') + '-' + Date.now();

  const filteredFiles = files.filter(file => {
    const filename = file.path.split('/').pop() || '';
    if (filename === '.env' || filename.startsWith('.env.')) {
      console.warn(`[GitHubExportAgent] Security warning: Blocked export of environmental file "${file.path}"`);
      return false;
    }
    return true;
  });

  if (!token) {
    console.warn('[GitHubExportAgent] GITHUB_TOKEN is not defined in the environment. Pushing to GitHub skipped.');
    console.log('[GitHubExportAgent] Fallback: Writing files locally into the workspace.');

    const localDemoDir = '/home/samsmart360/ProofPilot_V2/generated-demos/' + repoName;
    
    for (const file of filteredFiles) {
      const fullPath = localDemoDir + '/' + file.path;
      const parts = fullPath.split('/');
      parts.pop();
      const dir = parts.join('/');
      
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(fullPath, file.content, 'utf8');
    }

    console.log(`[GitHubExportAgent] Local fallback completed. Files written to: ${localDemoDir}`);
    return `https://github.com/mock-user/${repoName} (Local fallback: file://${localDemoDir})`;
  }

  try {
    const octokit = new Octokit({ auth: token });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const owner = user.login;
    console.log(`[GitHubExportAgent] Authenticated with GitHub user: ${owner}`);

    console.log(`[GitHubExportAgent] Creating public repository: ${repoName}`);
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Custom API Demo generated for: ${demoName}`,
      private: false,
      auto_init: false
    });

    console.log('[GitHubExportAgent] Creating initial commit with README.md...');
    const readmePath = 'README.md';
    const readmeContent = `# ${demoName}\nGenerated by ProofPilot Agentic Demo Generator.`;
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo: repoName,
      path: readmePath,
      message: 'initial commit',
      content: Buffer.from(readmeContent).toString('base64')
    });

    let branchRef = 'heads/main';
    let refData;
    try {
      const res = await octokit.rest.git.getRef({ owner, repo: repoName, ref: 'heads/main' });
      refData = res.data;
    } catch (e) {
      const res = await octokit.rest.git.getRef({ owner, repo: repoName, ref: 'heads/master' });
      refData = res.data;
      branchRef = 'heads/master';
    }
    const baseCommitSha = refData.object.sha;

    console.log(`[GitHubExportAgent] Uploading blobs for ${filteredFiles.length} files...`);
    const treeItems: any[] = [];
    for (const file of filteredFiles) {
      const { data: blob } = await octokit.rest.git.createBlob({
        owner,
        repo: repoName,
        content: file.content,
        encoding: 'utf-8'
      });

      treeItems.push({
        path: file.path,
        mode: '100644',
        type: 'blob',
        sha: blob.sha
      });
    }

    console.log('[GitHubExportAgent] Creating Git Tree...');
    const { data: tree } = await octokit.rest.git.createTree({
      owner,
      repo: repoName,
      base_tree: baseCommitSha,
      tree: treeItems
    });

    console.log('[GitHubExportAgent] Creating commit...');
    const { data: commit } = await octokit.rest.git.createCommit({
      owner,
      repo: repoName,
      message: 'Scaffold React + Express custom API demo files',
      tree: tree.sha,
      parents: [baseCommitSha]
    });

    console.log(`[GitHubExportAgent] Updating branch ref ${branchRef}...`);
    await octokit.rest.git.updateRef({
      owner,
      repo: repoName,
      ref: branchRef,
      sha: commit.sha
    });

    console.log(`[GitHubExportAgent] Successfully pushed demo code to GitHub!`);
    return repo.html_url;
  } catch (error: any) {
    console.error('[GitHubExportAgent] GitHub export failed:', error.message);
    throw new Error(`GitHub Export Agent failed: ${error.message}`);
  }
}
