import type { ClaimReport, DemoPlan, DemoRequest, GeneratedFile } from "../types.js";

export async function generateDemoFiles(
  input: DemoRequest,
  plan: DemoPlan,
  claimReport: ClaimReport
): Promise<GeneratedFile[]> {
  const safeClaims = claimReport.claims.map((claim: any) => claim.rewrite ?? claim.text);

  const isWeather = 
    input.apiName.toLowerCase().includes("weather") ||
    input.apiName.toLowerCase().includes("meteo") ||
    (input.context ?? "").toLowerCase().includes("weather") ||
    (input.context ?? "").toLowerCase().includes("meteo") ||
    (input.docsText ?? "").toLowerCase().includes("weather") ||
    (input.docsText ?? "").toLowerCase().includes("meteo");

  const isPayment = 
    input.apiName.toLowerCase().includes("payment") ||
    input.apiName.toLowerCase().includes("stripe") ||
    input.apiName.toLowerCase().includes("billing") ||
    (input.context ?? "").toLowerCase().includes("payment") ||
    (input.context ?? "").toLowerCase().includes("stripe") ||
    (input.context ?? "").toLowerCase().includes("billing");

  const fieldsJson = isWeather
    ? [
        { name: "latitude", value: "40.7128", confidence: 1.0 },
        { name: "longitude", value: "-74.0060", confidence: 1.0 },
        { name: "temperature", value: "22.5 °C", confidence: 0.99 },
        { name: "wind_speed", value: "14.2 km/h", confidence: 0.94 },
        { name: "condition", value: "Clear Sky", confidence: 0.91 }
      ]
    : isPayment
      ? [
          { name: "transaction_id", value: "tx_9a2b8c4d", confidence: 1.0 },
          { name: "customer_name", value: "Jane Rivera", confidence: 0.98 },
          { name: "amount", value: "1420.55 USD", confidence: 1.0 },
          { name: "status", value: "paid", confidence: 0.95 }
        ]
      : [
          { name: "payload_id", value: "pl_2026_99a", confidence: 1.0 },
          { name: "entity_name", value: "Jane Rivera", confidence: 0.94 },
          { name: "created_at", value: "2026-06-11", confidence: 1.0 },
          { name: "status", value: "completed", confidence: 0.88 }
        ];

  const appTsx = `
import { useState } from "react";
import "./style.css";

const mockFields = ${JSON.stringify(fieldsJson, null, 2)};

export default function App() {
  const [step, setStep] = useState(0);
  const screens = ${JSON.stringify(plan.screens, null, 2)};

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">Generated by ProofPilot</p>
        <h1>{${JSON.stringify(escapeForTemplate(plan.title))}}</h1>
        <p>{${JSON.stringify(escapeForTemplate(plan.story))}}</p>
      </section>

      <section className="grid">
        <aside className="card">
          <h2>Demo flow</h2>
          {screens.map((screen, index) => (
            <button key={screen} className={index === step ? "active step" : "step"} onClick={() => setStep(index)}>
              {index + 1}. {screen}
            </button>
          ))}
        </aside>

        <section className="card wide">
          <h2>{screens[step]}</h2>
          {step === 0 && <p>This walkthrough shows how {${JSON.stringify(escapeForTemplate(input.industry))}} leaders could evaluate {${JSON.stringify(escapeForTemplate(input.apiName))}} in a realistic workflow.</p>}
          {step === 1 && (
            <div className="upload">
              Configure and send request payload to {${JSON.stringify(escapeForTemplate(input.apiName))}}
              <br/>
              <span>Mock integration mode active</span>
            </div>
          )}
          {step === 2 && <FieldTable />}
          {step === 3 && <p>Inspect response values, adjust query settings if required, and submit payload to target system.</p>}
          {step === 4 && <pre>{JSON.stringify({ exported: true, fields: mockFields }, null, 2)}</pre>}
        </section>
      </section>

      <section className="card">
        <h2>Source-grounded claims</h2>
        <ul>{${JSON.stringify(safeClaims)}.map((claim) => <li key={claim}>{claim}</li>)}</ul>
      </section>
    </main>
  );
}

function FieldTable() {
  return <table><thead><tr><th>Field</th><th>Value</th><th>Confidence</th></tr></thead><tbody>{mockFields.map(f => <tr key={f.name}><td>{f.name}</td><td>{f.value}</td><td>{f.confidence ? Math.round(f.confidence * 100) : 100}%</td></tr>)}</tbody></table>;
}
`;

  return [
    { path: "README.md", content: readme(input, plan) },
    { path: "demo-script.md", content: demoScript(plan) },
    { path: "claim-check-report.md", content: claimReportMarkdown(claimReport) },
    { path: "frontend/package.json", content: JSON.stringify({ scripts: { dev: "vite", build: "vite build", preview: "vite preview" }, dependencies: { "@vitejs/plugin-react": "latest", vite: "latest", typescript: "latest", react: "latest", "react-dom": "latest" }, devDependencies: {} }, null, 2) },
    { path: "frontend/index.html", content: `<div id="root"></div><script type="module" src="/src/main.tsx"></script>` },
    { path: "frontend/src/main.tsx", content: `import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\ncreateRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);\n` },
    { path: "frontend/src/App.tsx", content: appTsx },
    { path: "frontend/src/style.css", content: css() },
    { path: "backend/package.json", content: JSON.stringify({ type: "module", scripts: { dev: "node src/server.js" }, dependencies: { express: "latest", cors: "latest" } }, null, 2) },
    { path: "backend/src/server.js", content: backendServer() }
  ];
}

function readme(input: DemoRequest, plan: DemoPlan) {
  return `# ${plan.title}\n\nGenerated API demo for **${input.industry}** using **${input.apiName}**.\n\n## Story\n\n${plan.story}\n\n## Screens\n\n${plan.screens.map((s) => `- ${s}`).join("\n")}\n\n## Endpoints Used\n\n${plan.endpointsUsed.map((e) => `- \`${e}\``).join("\n")}\n\n## Run\n\n\`\`\`bash\ncd frontend\nnpm install\nnpm run dev\n\`\`\`\n`;
}

function demoScript(plan: DemoPlan) {
  return `# Demo Script\n\n1. Open with the business problem.\n2. Show the generated workflow: ${plan.screens.join(" → ")}.\n3. Explain the API calls used.\n4. Show the claim-check report to prove unsupported claims were removed.\n5. Close with implementation next steps.\n`;
}

function claimReportMarkdown(report: ClaimReport) {
  return `# Claim Check Report\n\n| Claim | Status | Rewrite |\n|---|---|---|\n${report.claims.map((c: any) => `| ${c.text} | ${c.status} | ${c.rewrite ?? ""} |`).join("\n")}\n`;
}

function backendServer() {
  return `import express from "express";\nimport cors from "cors";\nconst app = express();\napp.use(cors());\napp.get('/api/mock/extraction', (_req,res)=>res.json({status:'completed', fields:[{name:'claim_number', value:'CLM-2026-001', confidence:0.98}]}));\napp.listen(3001,()=>console.log('Generated demo backend on http://localhost:3001'));\n`;
}

function css() {
  return `body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f7f7fb;color:#18181b}.shell{max-width:1100px;margin:auto;padding:32px}.hero,.card{background:white;border-radius:24px;padding:24px;box-shadow:0 12px 35px rgba(0,0,0,.08);margin-bottom:20px}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-size:12px;color:#6366f1}.grid{display:grid;grid-template-columns:320px 1fr;gap:20px}.wide{min-height:360px}.step{display:block;width:100%;text-align:left;margin:8px 0;padding:12px;border:1px solid #ddd;border-radius:14px;background:#fff;cursor:pointer}.active{border-color:#18181b;background:#f1f5f9}.upload{border:2px dashed #bbb;border-radius:18px;padding:48px;text-align:center;color:#555}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #e5e7eb;padding:10px;text-align:left}pre{background:#0f172a;color:#e2e8f0;padding:16px;border-radius:14px;overflow:auto}`;
}

function escapeForTemplate(value: string) {
  return value.replace(/`/g, "'").replace(/\$/g, "");
}
